NAMA          = input("Nama                   : ")
NIM           = input("NIM                    : ")
KELAS_PARALEL = input("Kelas Paralel          : ")
TTL           = input("Tempat/Tanggal Lahir   : ")
ALAMAT        = input("Alamat                 : ")
HOBBY         = input("Hobby                  : ")
NO_HP         = input("No. HP                 : ")

print(f"Nama                  : {NAMA}")
print(f"NIM                   : {NIM}")
print(f"Kelas Paralel         : {KELAS_PARALEL}")
print(f"Tempat/Tanggal Lahir  : {TTL}")
print(f"Alamat                : {ALAMAT}")
print(f"Hobby                 : {HOBBY}")
print(f"No. HP                : {NO_HP}")